In [1]:
import numpy as np

In [20]:
L = [1,2,3]

In [21]:
A = np.array(L)

In [6]:
B = np.array([1,2,3])

In [22]:
print( A )
print( L )
print( B )

[1 2 3]
[1, 2, 3]
[1 2 3]


In [67]:
for elem in L:
    print( elem )

1
2
3


In [65]:
M = np.random.random((3,3))

In [68]:
M

array([[ 0.87461554,  0.17346057,  0.75556535],
       [ 0.41713381,  0.16808272,  0.55476894],
       [ 0.7398645 ,  0.54355978,  0.64536952]])